# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger: none
pr: none

schedules:
- cron: "0 */8 * * *"
  displayName: Schedule Build
  branches:
    include:
    - master
  always: true

pool:
  vmImage: 'macos-latest'

steps:

- task: Bash@3
  displayName: Clone Heliport & Install pods
  inputs:
    targetType: 'inline'
    script: |
      #!/bin/bash
      git clone https://github.com/OpenIntelWireless/HeliPort.git
      cd HeliPort
      pod install
      pwd
      [ -e /Users/runner/work/1/s/changelog.md  ] && rm /Users/runner/work/1/s/changelog.md
      echo "# Release Notes" >> /Users/runner/work/1/s/changelog.md
      echo "## Latest HeliPort Changes " >> /Users/runner/work/1/s/changelog.md
      echo "*" "$(git log -n 1 --skip 0  --pretty=%B)" >> /Users/runner/work/1/s/changelog.md
      echo "*" "$(git log -n 1 --skip 1  --pretty=%B)" >> /Users/runner/work/1/s/changelog.md
      echo "*" "$(git log -n 1 --skip 2  --pretty=%B)" >> /Users/runner/work/1/s/changelog.md


- task: Bash@3
  displayName: Clone itlwm
  inputs:
    targetType: 'inline'
    script: |
      #!/bin/bash
      git clone https://github.com/OpenIntelWireless/itlwm.git
      cd itlwm
      echo "## Latest itlwm Changes" >> /Users/runner/work/1/s/changelog.md
      echo "*" "$(git log -n 1 --skip 0  --pretty=%B)" >> /Users/runner/work/1/s/changelog.md
      echo "*" "$(git log -n 1 --skip 1  --pretty=%B)" >> /Users/runner/work/1/s/changelog.md
      echo "*" "$(git log -n 1 --skip 2  --pretty=%B)" >> /Users/runner/work/1/s/changelog.md

- task: Xcode@5
  displayName: Build fwgen scheme
  inputs:
    actions: 'build'
    scheme: 'fwgen'
    sdk: 'macosx'
    configuration: 'Debug'
    xcWorkspacePath: '/Users/runner/work/1/s/itlwm/itlwm.xcodeproj'
    xcodeVersion: 'default' # Options: 8, 9, 10, default, specifyPath

- task: Xcode@5
  displayName: Build itlwm
  inputs:
    actions: 'build'
    scheme: 'itlwm'
    sdk: 'macosx'
    configuration: 'Debug'
    xcWorkspacePath: '/Users/runner/work/1/s/itlwm/itlwm.xcodeproj'
    xcodeVersion: 'default' # Options: 8, 9, 10, default, specifyPath

- task: Xcode@5
  displayName: Build itlwmx
  inputs:
    actions: 'build'
    scheme: 'itlwmx'
    sdk: 'macosx'
    configuration: 'Debug'
    xcWorkspacePath: '/Users/runner/work/1/s/itlwm/itlwm.xcodeproj'
    xcodeVersion: 'default' # Options: 8, 9, 10, default, specifyPath


- task: Xcode@5
  displayName: Build HeliPort
  inputs:
    actions: 'build'
    scheme: 'HeliPort'
    sdk: 'macosx'
    configuration: 'Debug'
    xcWorkspacePath: '/Users/runner/work/1/s/HeliPort/HeliPort.xcworkspace'
    xcodeVersion: 'default' # Options: 8, 9, 10, default, specifyPath

- task: Bash@3
  displayName: Check HeliPort.app
  inputs:
    targetType: 'inline'
    script: |
      #!/bin/bash
      cd /Users/runner/Library/Developer/Xcode/DerivedData/
      pwd
      ls
      cd HeliPort-gsvordzttwrowbcpijzllgtczvfw/Build/Products/Debug/
      ls
      
      BD="$(date +"%Y-%m-%d")" # Build Date
      echo "##vso[task.setvariable variable=BuildDate]$BD"

- task: Bash@3
  displayName: Check itlwm.kext & itlwmx.kext
  inputs:
    targetType: 'inline'
    script: |
      #!/bin/bash
      cd /Users/runner/Library/Developer/Xcode/DerivedData/
      pwd
      ls
      cd itlwm-abddpiaeqpzttlcatogytajfomqe/Build/Products/Debug/
      ls
      

- task: Bash@3
  displayName: Prepare Release Zip File
  inputs:
    targetType: 'inline'
    script: |
      #!/bin/bash
      cd /Users/runner/desktop/
      mkdir "HeliPort-itlwm-itlwmx"
      mv  /Users/runner/Library/Developer/Xcode/DerivedData/itlwm-abddpiaeqpzttlcatogytajfomqe/Build/Products/Debug/itlwm.kext /Users/runner/desktop/HeliPort-itlwm-itlwmx
      mv  /Users/runner/Library/Developer/Xcode/DerivedData/itlwm-abddpiaeqpzttlcatogytajfomqe/Build/Products/Debug/itlwmx.kext /Users/runner/desktop/HeliPort-itlwm-itlwmx
      mv /Users/runner/Library/Developer/Xcode/DerivedData/HeliPort-gsvordzttwrowbcpijzllgtczvfw/Build/Products/Debug/HeliPort.app /Users/runner/desktop/HeliPort-itlwm-itlwmx
      zip -r HeliPort-itlwm-itlwmx.zip HeliPort-itlwm-itlwmx


- task: GitHubRelease@1
  displayName: Github Release Assets
  inputs:
    gitHubConnection: 'github.com_1hbb'
    repositoryName: '1hbb/OpenIntelWireless-Factory'
    action: 'edit'
    target: '$(Build.SourceVersion)'
    tag: '$(BuildDate)'
    title: '$(BuildDate)'
    releaseNotesFilePath: '/Users/runner/work/1/s/changelog.md'
    assets: '/Users/runner/desktop/HeliPort-itlwm-itlwmx.zip'
    assetUploadMode: 'replace'
    isPreRelease: true
    changeLogCompareToRelease: 'lastNonDraftRelease'
    addChangeLog: false
