# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- master

pool:
  vmImage: 'macos-latest'

steps:

- task: Bash@3
  displayName: Check Changes
  inputs:
    targetType: 'inline'
    script: |
      #!/bin/bash
      git clone https://github.com/OpenIntelWireless/HeliPort.git
      cd HeliPort
      pod install
      pwd

- task: Xcode@5
  inputs:
    actions: 'build'
    scheme: 'HeliPort'
    sdk: 'macosx'
    configuration: 'Debug'
    xcWorkspacePath: '/Users/runner/work/1/s/HeliPort/HeliPort.xcworkspace'
    xcodeVersion: 'default' # Options: 8, 9, 10, default, specifyPath

- task: Bash@3
  displayName: Check Changes
  inputs:
    targetType: 'inline'
    script: |
      #!/bin/bash
      cd /Users/runner/Library/Developer/Xcode/DerivedData/
      pwd
      ls
      cd HeliPort-gsvordzttwrowbcpijzllgtczvfw/Build/Products/Debug/
      ls
      zip -r heliport.zip HeliPort.app

- task: Bash@3
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'), eq(variables['BuildCheck'], 'True'))
  displayName: Refresh Commits
  inputs:
    script: |
      git config --global credential.helper store
      echo https://$(PAT):x-oauth-basic@github.com >> ~/.git-credentials
      git config --global user.name 'Azure Pipelines'
      git config --global user.email '<>'
      cd ../b/RepoOperation/$(REPO)
      git add .
      git commit -m "Refresh Commits to $(BuildDate)"
      git push origin master

- task: GitHubRelease@0
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'), eq(variables['BuildCheck'], 'True'))
  displayName: 'Publish GitHub Release'
  inputs:
    gitHubConnection: release
    repositoryName: '$(Build.Repository.Name)'
    action: 'edit'
    target: '$(Build.SourceVersion)'
    tagSource: 'manual'
    tag: '$(BuildDate)'
    title: '$(BuildDate)'
    releaseNotesFile: '$(Build.ArtifactStagingDirectory)/ReleaseNotes.md'
    assets: '/Users/runner/Library/Developer/Xcode/DerivedData/HeliPort-gsvordzttwrowbcpijzllgtczvfw/Build/Products/Debug/heliport.zip'
    addChangeLog: false
    isPreRelease: true